from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column

from app.core.base import BaseModel, SpaceScopedMixin


class InboxItem(BaseModel, SpaceScopedMixin):
    """A persisted, write-time-generated notification (Checkpoint 2.4) — not
    a read-model like Calendar's agenda. Generated by direct service-to-
    service calls (e.g. tasks.service calling inbox.service.create_item()),
    never an event bus.

    title is a SNAPSHOT taken at generation time, not looked up live from
    task_id — an inbox item is a record of what was true when it was
    generated (the same pattern every real notification/activity feed
    uses), so it must not silently change if the source Task is edited
    later. task_id is kept only as a reference back to the source (e.g. for
    a future "go to task" action); it plays no part in rendering the title.

    No life_area_id: an InboxItem isn't itself life-area-classified content
    the way Task/CalendarEvent are — it's a notification ABOUT something
    that may have a life area, reachable via task_id if ever needed, not an
    independent classification of the notification itself.

    read_at / archived_at are both persisted lifecycle fields, never
    client-computed. "Dismissed" reuses archived_at rather than a separate
    dismissed_at — for this MVP they mean the same thing operationally
    ("stop showing this in the active inbox, keep the row"), so this
    intentionally reuses the exact convention Task/CalendarEvent already
    use for soft delete instead of inventing a second name for the same
    mechanism.
    """

    __tablename__ = "inbox_items"

    title: Mapped[str] = mapped_column(String, nullable=False)
    task_id: Mapped[int | None] = mapped_column(ForeignKey("tasks.id"), index=True, nullable=True)
    read_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    archived_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
