"""add attention exposures

Revision ID: 48d161b6a393
Revises: 8cf6e6c7fc03
Create Date: 2026-10-01 20:05:05.631345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48d161b6a393'
down_revision: Union[str, None] = '8cf6e6c7fc03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_exposures',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('inbox_item_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('surface', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exposure_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('surfaced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acted_on_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('num_nonnulls(task_id, event_id, inbox_item_id) = 1', name='ck_attention_exposures_exactly_one_source'),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['inbox_items.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_exposures_event_id'), 'attention_exposures', ['event_id'], unique=False)
    op.create_index(op.f('ix_attention_exposures_inbox_item_id'), 'attention_exposures', ['inbox_item_id'], unique=False)
    op.create_index(op.f('ix_attention_exposures_space_id'), 'attention_exposures', ['space_id'], unique=False)
    op.create_index(op.f('ix_attention_exposures_task_id'), 'attention_exposures', ['task_id'], unique=False)
    op.create_index(op.f('ix_attention_exposures_user_id'), 'attention_exposures', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attention_exposures_user_id'), table_name='attention_exposures')
    op.drop_index(op.f('ix_attention_exposures_task_id'), table_name='attention_exposures')
    op.drop_index(op.f('ix_attention_exposures_space_id'), table_name='attention_exposures')
    op.drop_index(op.f('ix_attention_exposures_inbox_item_id'), table_name='attention_exposures')
    op.drop_index(op.f('ix_attention_exposures_event_id'), table_name='attention_exposures')
    op.drop_table('attention_exposures')
    # ### end Alembic commands ###
