"""add spaces, life_areas, tasks

Revision ID: 5601cda571d7
Revises: 1448abc9f920
Create Date: 2026-09-22 16:56:40.482452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5601cda571d7'
down_revision: Union[str, None] = '1448abc9f920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('life_areas',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_life_areas_slug'), 'life_areas', ['slug'], unique=True)
    op.create_table('spaces',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('life_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['life_area_id'], ['life_areas.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_life_area_id'), 'tasks', ['life_area_id'], unique=False)
    op.create_index(op.f('ix_tasks_space_id'), 'tasks', ['space_id'], unique=False)
    # ### end Alembic commands ###

    # Data seeding, not just schema. Unlike the single User row (which needs
    # a secret only a human should choose, hence auth's separate seed.py
    # script), neither the default space nor the life-area list involves any
    # secret content — both are seeded right here so a fresh `alembic
    # upgrade head` is immediately usable with no extra manual step.
    spaces_table = sa.table(
        "spaces",
        sa.column("name", sa.String),
        sa.column("is_default", sa.Boolean),
    )
    op.bulk_insert(spaces_table, [{"name": "Personal", "is_default": True}])

    life_areas_table = sa.table(
        "life_areas",
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
    )
    op.bulk_insert(
        life_areas_table,
        [
            {"name": "Work", "slug": "work"},
            {"name": "Personal", "slug": "personal"},
            {"name": "Learning", "slug": "learning"},
            {"name": "Career", "slug": "career"},
            {"name": "Projects", "slug": "projects"},
            {"name": "Ideas", "slug": "ideas"},
            {"name": "Teaching", "slug": "teaching"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_space_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_life_area_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_life_areas_slug'), table_name='life_areas')
    op.drop_table('life_areas')
    # ### end Alembic commands ###
