"""add memories table and executed_memory_id

Revision ID: 747169a6185c
Revises: f2566923f692
Create Date: 2026-09-25 11:42:02.834222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '747169a6185c'
down_revision: Union[str, None] = 'f2566923f692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_chat_message_id', sa.Integer(), nullable=False),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_source_chat_message_id'), 'memories', ['source_chat_message_id'], unique=False)
    op.create_index(op.f('ix_memories_space_id'), 'memories', ['space_id'], unique=False)
    op.create_index(op.f('ix_memories_superseded_by_id'), 'memories', ['superseded_by_id'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.add_column('proposed_actions', sa.Column('executed_memory_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_proposed_actions_executed_memory_id'), 'proposed_actions', ['executed_memory_id'], unique=False)
    op.create_foreign_key(
        'fk_proposed_actions_executed_memory_id_memories', 'proposed_actions', 'memories', ['executed_memory_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_proposed_actions_executed_memory_id_memories', 'proposed_actions', type_='foreignkey')
    op.drop_index(op.f('ix_proposed_actions_executed_memory_id'), table_name='proposed_actions')
    op.drop_column('proposed_actions', 'executed_memory_id')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_superseded_by_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_space_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_source_chat_message_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
