"""add timezone name to attention exposures

Revision ID: b2817c0088e9
Revises: 48d161b6a393
Create Date: 2026-10-01 21:06:38.121711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2817c0088e9'
down_revision: Union[str, None] = '48d161b6a393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attention_exposures', sa.Column('timezone_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attention_exposures', 'timezone_name')
    # ### end Alembic commands ###
