"""add calendar_events

Revision ID: cd72560d278a
Revises: 5601cda571d7
Create Date: 2026-09-22 17:24:49.454010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd72560d278a'
down_revision: Union[str, None] = '5601cda571d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('life_area_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('ends_at IS NULL OR ends_at >= starts_at', name='ck_calendar_events_ends_after_starts'),
    sa.ForeignKeyConstraint(['life_area_id'], ['life_areas.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_life_area_id'), 'calendar_events', ['life_area_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_space_id'), 'calendar_events', ['space_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_space_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_life_area_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
