"""add proposed actions

Revision ID: f2566923f692
Revises: a8a367324995
Create Date: 2026-09-24 22:40:43.310637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2566923f692'
down_revision: Union[str, None] = 'a8a367324995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_actions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_chat_message_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_task_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['executed_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['source_chat_message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_actions_executed_task_id'), 'proposed_actions', ['executed_task_id'], unique=False)
    op.create_index(op.f('ix_proposed_actions_source_chat_message_id'), 'proposed_actions', ['source_chat_message_id'], unique=False)
    op.create_index(op.f('ix_proposed_actions_space_id'), 'proposed_actions', ['space_id'], unique=False)
    op.create_index(op.f('ix_proposed_actions_user_id'), 'proposed_actions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proposed_actions_user_id'), table_name='proposed_actions')
    op.drop_index(op.f('ix_proposed_actions_space_id'), table_name='proposed_actions')
    op.drop_index(op.f('ix_proposed_actions_source_chat_message_id'), table_name='proposed_actions')
    op.drop_index(op.f('ix_proposed_actions_executed_task_id'), table_name='proposed_actions')
    op.drop_table('proposed_actions')
    # ### end Alembic commands ###
