"""add correlation_id to ai_traces

Revision ID: f646f62657a8
Revises: 747169a6185c
Create Date: 2026-09-25 18:18:29.069793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f646f62657a8'
down_revision: Union[str, None] = '747169a6185c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_traces', sa.Column('correlation_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_ai_traces_correlation_id'), 'ai_traces', ['correlation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_traces_correlation_id'), table_name='ai_traces')
    op.drop_column('ai_traces', 'correlation_id')
    # ### end Alembic commands ###
